### ISSUE TITLE
Create account failes with 1043

### ISSUE THREAD

**Issue by AgenChicken24** [Exploited7/outlook-account-creator#2]
When creating an account it fails with code 1043. This is the response of the request.
![photo_2024-05-24_16-53-18](https://github.com/Exploited7/outlook-account-creator/assets/64702468/fa7f5d6a-361b-4904-aa7c-73a3a435444b)
![photo_2024-05-24_16-53-51](https://github.com/Exploited7/outlook-account-creator/assets/64702468/496a54d1-04a2-4ec0-aecc-87c4b42e8564)

**Comment by Exploited7** [comment]
Hello , thanks for your report . 
this started coming last days due to the captcha solvers , thats not a tool problem sir . 
thanks .

**Comment by AgenChicken24** [comment]
Hi, thank you for responding.
If the issue is with the captcha solvers, what workaround do you suggest?
Since this error code doesn't provide any information, could you please explain what the 1043 code signifies or where I should look for this information?

**Comment by Exploited7** [comment]
1- You could try to change proxies to another good and paid providers and make sure use sticky ones 
for ex : add 1k sticky proxies in your txt file and try . because when you use sticky IP you are matching the ip with all requests . 

2- Sorry but actually i don't think there are any other good providers , but you could try with both providers that i added in the tool they looks good i genned 3k accounts and i got only 30 bad . 

Regards.

**Comment by AgenChicken24** [comment]
Thanks,
WIll try out those solutions.

На сб, 25.05.2024 г. в 2:23 Manuel Emad ***@***.***> написа:

**Comment by AgenChicken24** [comment]
Hello, again.

I tried your suggestion of using "2captcha", "ez-captcha" and "capsolver" with multiple proxies bought from "iproyal", but I am still unable to create even one account.

Can you give some information about this issue? Such as, when is this happening and under what conditions does it occur?

**Comment by fripokoff** [comment]
Try different countries, the country of the creator Egypt seems to work USA too but not the European proxies
